version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy:v0r0
  api-user-p3:
    build:
      context: ./udagram-api-user
    image: udagram-api-user:v0r0
  api-feed-p3:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed:v0r0
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local